---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:focal
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: ansible
